## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

import requests as req
from pprint import pprint as p

# Import API key
from config import g_api_key

# Configure gmaps API key
gmaps.configure(api_key=g_api_key)

# Base URL
url_1 = 'https://www.google.com/maps/dir/?api=' + g_api_key
url_2 = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?'

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Resources/WeatherPy_database.csv")

# Check imported data set
city_data_df.head()
print(len(city_data_df.index))

2031

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = input("Minimum Temperature: ")
max_temp = input("Maximum Temperature: ")

# convert to integer
min_temp = int(min_temp)
max_temp = int(max_temp)

print (f'min temp {min_temp}, max temp {max_temp}')
print (f'min temp data type {type(min_temp)}, max temp data type {type(max_temp)}')

min temp 45, max temp 85
min temp data type <class 'int'>, max temp data type <class 'int'>

In [4]:
city_data_df.dtypes

City_ID                  int64
City                    object
Lat                    float64
Lng                    float64
Max Temp               float64
Current Description     object
Rain (inches)          float64
Snow (inches)          float64
Humidity                 int64
Cloudiness               int64
Wind Speed             float64
Country                 object
dtype: object

In [5]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
filtered_city_data_df = city_data_df.loc[(city_data_df['Max Temp']>= min_temp) & (city_data_df['Max Temp']<= max_temp)]

filtered_city_data_df
print(len(filtered_city_data_df.index))

1168

In [6]:
# 4a. Determine if there are any empty rows.
filtered_city_data_df.count()

City_ID                1168
City                   1168
Lat                    1168
Lng                    1168
Max Temp               1168
Current Description    1168
Rain (inches)          1168
Snow (inches)          1168
Humidity               1168
Cloudiness             1168
Wind Speed             1168
Country                1158
dtype: int64

In [7]:
# 4b. Drop any empty rows and create a new DataFrame that doesnâ€™t have empty rows.
filtered_city_data_df = filtered_city_data_df.dropna()

In [8]:
print(len(filtered_city_data_df.index))

1158

In [9]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = []
hotel_df = filtered_city_data_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

x = [i for i in range(len(hotel_df.index))]

# 5b. Create a new column "Hotel Name"
hotel_df['Hotel Name'] = '' #np.nan
hotel_df['index_'] = x

hotel_df = hotel_df.set_index('index_')
print(len(hotel_df.index))

1158

In [10]:
#df.loc[(df['Salary_in_1000']>=100) & (df['Age']< 60) & (df['FT_Team'].str.startswith('S')),['Name','FT_Team']]
lat__ = hotel_df['Lat']
lng__ = hotel_df['Lng']

#lat__.iloc[0]
#lng__.iloc[0]
#
#print (lat__)
#print (lng__)

In [13]:
# 6a. Set parameters to search for hotels within 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_api_key
}

# 6b. Iterate through the hotel DataFrame.
for i, city in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat_i = str(lat__.iloc[i]) 
    lng_i = str(lng__.iloc[i])


    # creating location key on 1st pass // replacing lat&long string on subsequent passes
    params["location"] = f"{lat_i}%2C{lng_i}"
    #print (params)

    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    # this is above // url_2
    #print (params)
    hotel_url = url_2 + 'location=' + str(params['location']) + '&radius=' + str(params['radius']) + '&type=' + str(params['type']) + '&key=' + g_api_key
    #print (hotel_url)

    # 6e. Make request and retrieve the JSON data from the search. 
    try:
        city_hotel = req.get(hotel_url).json()
        #p(city_hotel)
        
        res_status = city_hotel['status']
        #print (res_status)

        if (res_status == "ZERO_RESULTS"):
            print("Hotel not found in City. Skipping...")
            pass       

    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city
        hotel_name = city_hotel['results'][0]['name']
        hotel_df.loc[i,'Hotel Name']= hotel_name 

    except (IndexError):
        print("Hotel not found in City. Skipping...")
        pass

Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...
Hotel not found in City. Skipping...

In [14]:
print(hotel_df)

                City Country  Max Temp Current Description      Lat       Lng  \
index_
0           Belmonte      BR     77.50       moderate rain -15.8631  -38.8828
1       Saint George      US     50.47           clear sky  37.1041 -113.5841
2             Avarua      CK     75.25    scattered clouds -21.2078 -159.7750
3          Kathmandu      NP     46.62          few clouds  27.7167   85.3167
4          Busselton      AU     72.09           clear sky -33.6500  115.3333
...              ...     ...       ...                 ...      ...       ...
1153    North Platte      US     58.06           clear sky  41.1239 -100.7654
1154          Naliya      IN     67.35           clear sky  23.2667   68.8333
1155      Pandharpur      IN     71.13           clear sky  17.6667   75.3333
1156      Nkhata Bay      MW     72.41          light rain -11.6066   34.2907
1157        Moranbah      AU     71.56       broken clouds -22.0016  148.0466

                                               Hotel Name
index_
0                             Pousada Monte Carmelo O PÃ£o
1                             Best Western Plus Abbey Inn
2                                            Paradise Inn
3                                 Hotel Shanker Kathmandu
4                                 Observatory Guest House
...                                                   ...
1153    Holiday Inn Express & Suites North Platte, an ...
1154                                  jadeja jayendrasinh
1155                    Pandharinath Lodge and Restaurant
1156                                       Mayoka Village
1157                    Direct Hotels - Monterey Moranbah

[1158 rows x 7 columns]

In [15]:
hotel_df.head(20)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
index_,,,,,,,
0,Belmonte,BR,77.50,moderate rain,-15.8631,-38.8828,Pousada Monte Carmelo O PÃ£o
1,Saint George,US,50.47,clear sky,37.1041,-113.5841,Best Western Plus Abbey Inn
2,Avarua,CK,75.25,scattered clouds,-21.2078,-159.7750,Paradise Inn
3,Kathmandu,NP,46.62,few clouds,27.7167,85.3167,Hotel Shanker Kathmandu
4,Busselton,AU,72.09,clear sky,-33.6500,115.3333,Observatory Guest House
5,Rikitea,PF,77.07,overcast clouds,-23.1203,-134.9692,People ThankYou
6,Pangkalanbuun,ID,76.55,overcast clouds,-2.6833,111.6167,Grand Kecubung Hotel
7,Taoudenni,ML,80.53,overcast clouds,22.6783,-3.9836,
8,Ushuaia,AR,58.66,scattered clouds,-54.8000,-68.3000,Albatross Hotel
9,Hermanus,ZA,80.80,clear sky,-34.4187,19.2345,Misty Waves Boutique Hotel
10,Lebu,CL,64.40,scattered clouds,-37.6167,-73.6500,Hostal Las Lilas
11,Bluff,NZ,61.81,overcast clouds,-46.6000,168.3333,Bluff Homestead - Guesthouse & Campervan Park
12,Kapaa,US,73.72,light rain,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
13,East London,ZA,74.34,scattered clouds,-33.0153,27.9116,Tu Casa
14,Kieta,PG,79.88,overcast clouds,-6.2167,155.6333,Uruna Bay Retreat
15,Ghanzi,BW,80.98,overcast clouds,-21.5667,21.7833,Ghanzi Farmhouse
16,Luganville,VU,78.62,light rain,-15.5333,167.1667,The Espiritu Hotel
17,Punta Alta,AR,84.65,clear sky,-38.8759,-62.0736,Center Hotel Punta Alta
18,Vaini,TO,80.96,light rain,-21.2000,-175.2000,Keleti Beach Resort
19,Mar Del Plata,AR,78.82,clear sky,-38.0023,-57.5575,Gran Hotel Mar del Plata

In [16]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df = hotel_df.loc[hotel_df['Hotel Name'] != '']

In [17]:
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
index_,,,,,,,
0,Belmonte,BR,77.50,moderate rain,-15.8631,-38.8828,Pousada Monte Carmelo O PÃ£o
1,Saint George,US,50.47,clear sky,37.1041,-113.5841,Best Western Plus Abbey Inn
2,Avarua,CK,75.25,scattered clouds,-21.2078,-159.7750,Paradise Inn
3,Kathmandu,NP,46.62,few clouds,27.7167,85.3167,Hotel Shanker Kathmandu
4,Busselton,AU,72.09,clear sky,-33.6500,115.3333,Observatory Guest House
...,...,...,...,...,...,...,...
1153,North Platte,US,58.06,clear sky,41.1239,-100.7654,"Holiday Inn Express & Suites North Platte, an ..."
1154,Naliya,IN,67.35,clear sky,23.2667,68.8333,jadeja jayendrasinh
1155,Pandharpur,IN,71.13,clear sky,17.6667,75.3333,Pandharinath Lodge and Restaurant
1156,Nkhata Bay,MW,72.41,light rain,-11.6066,34.2907,Mayoka Village
1157,Moranbah,AU,71.56,broken clouds,-22.0016,148.0466,Direct Hotels - Monterey Moranbah

In [18]:
# 8a. Create the output File (CSV)

output_data_file = "Resources/HotelPy_Database.csv"

# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [19]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
    <dt>Hotel Name
    </dt>
        <dd>{Hotel Name}
        </dd>
    <dt>City
    </dt>
        <dd>{City}
        </dd>
    <dt>Country
    </dt>
        <dd>{Country}
        </dd>
    <dt>Weather
    </dt>
        <dd>{Current Description}
        </dd>
    <dt>Max Temp
    </dt>
        <dd>{Max Temp} Â°F
        </dd>

</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [20]:
locations.reset_index(drop=True, inplace=True)

In [21]:
locations

          Lat       Lng
0    -15.8631  -38.8828
1     37.1041 -113.5841
2    -21.2078 -159.7750
3     27.7167   85.3167
4    -33.6500  115.3333
...       ...       ...
1083  41.1239 -100.7654
1084  23.2667   68.8333
1085  17.6667   75.3333
1086 -11.6066   34.2907
1087 -22.0016  148.0466

[1088 rows x 2 columns]

In [22]:
# 10c. Plot map
#fig = gmaps.figure()

# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

# 11a. Add a marker layer for each city to the map. 
markers = gmaps.marker_layer(locations)

# 11b. Display the figure
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))